# Generated by Django 4.0.3 on 2022-08-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(max_length=100, verbose_name='хеш транзакции')),
                ('transaction_sum', models.FloatField(max_length=20, verbose_name='сумма транзакции')),
                ('transaction_description', models.TextField(default='', max_length=200, verbose_name='описание транзакции')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
    ]
