# Generated by Django 4.1 on 2022-08-27 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_hash',
            new_name='transaction_id',
        ),
    ]
